Repository tracel-ai/burn, pull requests merged in 2024-08, with the labels that each got.

#2120 bug fix: adding bounds checking to pad ONNX inputs
  crates/burn-import/src/onnx/op_configuration.rs
Labels: bug, onnx

#2165 Gather CPA to CubeCL
  crates/burn-core/Cargo.toml
  crates/burn-jit/src/kernel/index/gather.rs
  examples/text-classification/Cargo.toml
Labels: cube_rewrite

#2195 pad-input-fix: adding support for pads as attributes
  crates/burn-import/src/onnx/op_configuration.rs
Labels: onnx

#2196 Tensor type indent fix
  crates/burn-import/src/burn/graph.rs
  crates/burn-import/src/burn/ty.rs
Labels: onnx

#2063 Refactor xtask to use tracel-xtask and refactor CI workflow
  .cargo/config.toml
  .github/actions/setup-llvmpipe-lavapipe/action.yml
  .github/workflows/ci.yml
  .github/workflows/publish-template.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  _typos.toml
  backend-comparison/src/burnbenchapp/runner.rs
  crates/burn-core/tests/test_derive_config.rs
  crates/burn-core/tests/test_derive_module.rs
  crates/burn-core/tests/test_derive_record.rs
  crates/burn-core/tests/test_record_resilience.rs
  crates/burn-import/onnx-tests/tests/sub/sub.py
  crates/burn-import/onnx-tests/tests/sub/sub_int.py
  crates/burn-import/onnx-tests/tests/test_onnx.rs
  crates/burn-import/onnx-tests/tests/test_record_type.rs
  crates/burn-import/pytorch-tests/tests/test_mod.rs
  crates/burn-no-std-tests/tests/test_integration.rs
  examples/simple-regression/Cargo.toml
  run-checks.ps1
  run-checks.sh
  xtask/Cargo.toml
  xtask/src/commands/books.rs
  xtask/src/commands/build.rs
  xtask/src/commands/doc.rs
  xtask/src/commands/mod.rs
  xtask/src/commands/test.rs
  xtask/src/commands/validate.rs
  xtask/src/dependencies.rs
  xtask/src/logging.rs
  xtask/src/main.rs
  xtask/src/publish.rs
  xtask/src/runchecks.rs
  xtask/src/utils/cargo.rs
  xtask/src/utils/mdbook.rs
  xtask/src/utils/mod.rs
  xtask/src/utils/process.rs
  xtask/src/utils/rustup.rs
  xtask/src/utils/time.rs
  xtask/src/utils/workspace.rs
  xtask/src/vulnerabilities.rs
Labels: infrastructure
