Repository tracel-ai/burn, pull requests merged in 2024-02, with the labels that each got.

#1219 Add a semantic versioning checker
  .github/workflows/semver-checks.yml
Labels: infrastructure

#1209 `NaN` and `Inf` detection in `assert_approx_eq`
  burn-candle/src/lib.rs
  burn-tensor/src/tensor/data.rs
Labels: bug

#1235 [CI] Simplify CI binaries updating
  .github/workflows/dependencies.yml
  .github/workflows/test.yml
  .github/workflows/vulnerabilities.yml
Labels: infrastructure

#1303 [CI] Add workflow to test dependencies and update Cargo.lock
  .github/workflows/combine-dependabot-prs.yml
  .github/workflows/update-cargo-lock.yml
Labels: infrastructure

#1285 [backend-comparison] Add GitHub authentication to burnbench CLI
  Cargo.lock
  Cargo.toml
  backend-comparison/Cargo.toml
  backend-comparison/README.md
  backend-comparison/src/bin/burnbench.rs
  backend-comparison/src/burnbenchapp/auth.rs
  backend-comparison/src/burnbenchapp/base.rs
  backend-comparison/src/burnbenchapp/mod.rs
Labels: benchmark

#1323 Pytorch config extraction
  Cargo.lock
  Cargo.toml
  burn-book/src/import/pytorch-model.md
  burn-core/Cargo.toml
  burn-core/src/record/serde/data.rs
  burn-import/Cargo.toml
  burn-import/data/mnist.pt
  burn-import/pytorch-tests/tests/config/export_weights.py
  burn-import/pytorch-tests/tests/config/mod.rs
  burn-import/pytorch-tests/tests/config/weights_with_config.pt
  burn-import/pytorch-tests/tests/mod.rs
  burn-import/src/pytorch/config.rs
  burn-import/src/pytorch/error.rs
  burn-import/src/pytorch/mod.rs
Labels: enhancement
