Repository tracel-ai/burn, pull requests merged in 2024-04, with the labels that each got.

#1375 Make backend names in JSON reports match burnbench CLI
  backend-comparison/benches/binary.rs
  backend-comparison/benches/conv_transpose2d.rs
  backend-comparison/benches/custom_gelu.rs
  backend-comparison/benches/data.rs
  backend-comparison/benches/matmul.rs
  backend-comparison/benches/max_pool2d.rs
  backend-comparison/benches/unary.rs
  backend-comparison/src/lib.rs
  backend-comparison/src/persistence/base.rs
Labels: performance, benchmark

#1567 [backend-comparison] Add all choice to --benches and --backends
  backend-comparison/src/burnbenchapp/base.rs
  backend-comparison/src/persistence/base.rs
Labels: benchmark

#1568 [backend-comparison] Rework burnbench output to be nicer and more compact
  Cargo.lock
  Cargo.toml
  backend-comparison/Cargo.toml
  backend-comparison/src/burnbenchapp/base.rs
  backend-comparison/src/burnbenchapp/mod.rs
  backend-comparison/src/burnbenchapp/progressbar.rs
  backend-comparison/src/burnbenchapp/reports.rs
  backend-comparison/src/burnbenchapp/runner.rs
  backend-comparison/src/burnbenchapp/term/base.rs
  backend-comparison/src/burnbenchapp/term/mod.rs
  backend-comparison/src/burnbenchapp/tui/base.rs
  backend-comparison/src/burnbenchapp/tui/components/mod.rs
  backend-comparison/src/burnbenchapp/tui/components/regions.rs
  backend-comparison/src/burnbenchapp/tui/mod.rs
  backend-comparison/src/persistence/base.rs
  backend-comparison/src/persistence/system_info.rs
Labels: benchmark

#1553 WindowDataset/windows function
  burn-book/src/building-blocks/dataset.md
  crates/burn-dataset/src/dataset/base.rs
  crates/burn-dataset/src/dataset/mod.rs
  crates/burn-dataset/src/dataset/window.rs
Labels: feature

#1035 implement bidirectional lstm
  burn-book/src/building-blocks/module.md
  crates/burn-core/src/nn/rnn/gate_controller.rs
  crates/burn-core/src/nn/rnn/lstm.rs
Labels: enhancement

#1649 [guide] Remove ambiguity lib vs. executable
  burn-book/book.toml
  burn-book/src/basic-workflow/README.md
  burn-book/src/basic-workflow/backend.md
  burn-book/src/basic-workflow/inference.md
  burn-book/src/basic-workflow/model.md
  burn-book/src/getting-started.md
  examples/guide/examples/guide.rs
  examples/guide/src/lib.rs
  examples/guide/src/main.rs
Labels: documentation

#1700 Fix ONNX linear bug by not updating shape for linear if not present
  crates/burn-import/src/onnx/dim_inference.rs
Labels: bug

#1679 Handle ndarray matmul broadcasting
  crates/burn-ndarray/src/ops/matmul.rs
  crates/burn-tensor/src/tests/ops/matmul.rs
Labels: bug

#1685 New CUDA runtime
  Cargo.lock
  backend-comparison/Cargo.toml
  crates/burn-compute/src/server.rs
  crates/burn-core/Cargo.toml
  crates/burn-cuda/Cargo.toml
  crates/burn-cuda/README.md
  crates/burn-cuda/src/compiler/base.rs
  crates/burn-cuda/src/compiler/binary.rs
  crates/burn-cuda/src/compiler/body.rs
  crates/burn-cuda/src/compiler/element.rs
  crates/burn-cuda/src/compiler/instruction.rs
  crates/burn-cuda/src/compiler/mod.rs
  crates/burn-cuda/src/compiler/settings.rs
  crates/burn-cuda/src/compiler/shader.rs
  crates/burn-cuda/src/compiler/unary.rs
  crates/burn-cuda/src/compute/mod.rs
  crates/burn-cuda/src/compute/server.rs
  crates/burn-cuda/src/compute/storage.rs
  crates/burn-cuda/src/device.rs
  crates/burn-cuda/src/element.rs
  crates/burn-cuda/src/lib.rs
  crates/burn-cuda/src/runtime.rs
  crates/burn-jit/Cargo.toml
  crates/burn-jit/src/codegen/compiler.rs
  crates/burn-jit/src/codegen/dialect/gpu/macros.rs
  crates/burn-jit/src/codegen/dialect/gpu/operation.rs
  crates/burn-jit/src/codegen/dialect/gpu/procedure/base.rs
  crates/burn-jit/src/codegen/dialect/gpu/procedure/index.rs
  crates/burn-jit/src/codegen/dialect/gpu/procedure/mod.rs
  crates/burn-jit/src/codegen/dialect/gpu/shader.rs
  crates/burn-jit/src/codegen/dialect/gpu/variable.rs
  crates/burn-jit/src/codegen/dialect/gpu/vectorization.rs
  crates/burn-jit/src/codegen/kernel.rs
  crates/burn-jit/src/compute/kernel.rs
  crates/burn-jit/src/element.rs
  crates/burn-jit/src/fusion/kernel.rs
  crates/burn-jit/src/fusion/tracing/builder.rs
  crates/burn-jit/src/kernel/matmul/base.rs
  crates/burn-jit/src/lib.rs
  crates/burn-jit/src/runtime.rs
  crates/burn-jit/src/template/base.rs
  crates/burn-tensor/src/tests/clone_invariance.rs
  crates/burn-wgpu/src/compiler/wgsl/body.rs
  crates/burn-wgpu/src/compiler/wgsl/compiler.rs
  crates/burn-wgpu/src/compiler/wgsl/shader.rs
  crates/burn/Cargo.toml
  xtask/src/runchecks.rs
  xtask/src/utils/mod.rs
  xtask/src/utils/workspace.rs
Labels: feature
